name: gestion_magasin
description: "Application de gestion de magasin développée avec Flutter pour desktop Windows."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Database
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # UI
  cupertino_icons: ^1.0.6
  file_picker: ^10.3.7

  # Network
  shared_preferences: ^2.2.2
  
  # Security
  bcrypt: ^1.1.3

  # Utils
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  csv: ^6.0.0
  excel: ^4.0.6
  crypto: ^3.0.7
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/